import brick from '../assets/painted/brick.webp';
import lumber from '../assets/painted/lumber.webp';
import wool from '../assets/painted/wool.webp';
import grain from '../assets/painted/grain.webp';
import ore from '../assets/painted/ore.webp';
import desert from '../assets/painted/desert.webp';
import gold from '../assets/painted/gold.webp';
import sea from '../assets/painted/sea.webp';
import fog from '../assets/painted/fog.webp';
import knight from '../assets/painted/knight.webp';
import victoryPoint from '../assets/painted/victoryPoint.webp';
import roadBuilding from '../assets/painted/roadBuilding.webp';
import yearOfPlenty from '../assets/painted/yearOfPlenty.webp';
import monopoly from '../assets/painted/monopoly.webp';
export const CARD_ARTWORK = {brick, lumber, wool, grain, ore, knight, victoryPoint, roadBuilding, yearOfPlenty, monopoly};
export const TERRAIN_ARTWORK = {forest:lumber, hills:brick, pasture:wool, fields:grain, mountains:ore, desert, gold, sea, fog};
