import {useState} from 'react';
import {CITY_TRACKS,CK_ACTION_NAMES,CK_ACTION_COSTS,friendly,vertexPoint,positionId} from './citiesKnightsView';
import GameIcon from './GameIcon';
import {KnightShape} from './CitiesKnightsPiece';
import CitiesKnightsChoice from './CitiesKnightsChoice';
export function CityCost({cost}) {return <span className="ck-cost">{Object.entries(cost||{}).map(([type,count])=><span key={type} aria-label={`${count} ${type}`}><GameIcon name={type} size={14}/>{count}</span>)}</span>;}
export function BarbarianVoyage({game}) {const state=game.citiesKnights;if(!state)return null;const b=state.barbarian;const strength=Object.values(state.knights).filter(k=>k.active).reduce((n,k)=>n+k.strength,0);const cityPositions=new Set(Object.entries(game.vertices||{}).filter(([,v])=>v.building==='city').map(([key])=>positionId(vertexPoint(key))));
  const last=state.lastBarbarianAttack;
  return <section className="ck-voyage" aria-label="Barbarian voyage"><div className="ck-voyage-heading"><GameIcon name={state.eventDie||'barbarian'} size={23}/><span>{state.eventDie?`${friendly(state.eventDie)} event`:'Barbarian voyage'}</span><strong>{b.max-b.position} steps away</strong></div>
    <div className="ck-voyage-track" role="meter" aria-label="Barbarian position" aria-valuemin={0} aria-valuemax={b.max} aria-valuenow={b.position}>{Array.from({length:b.max+1},(_,i)=><span key={i} className={i===b.position?'is-current':i<b.position?'is-passed':''}>{i===b.max?<GameIcon name="city" size={16}/>:<i/>}</span>)}<b className="ck-voyage-ship" aria-hidden="true" style={{left:`${b.position/(b.max+1)*100}%`}}><GameIcon name="barbarian" size={19}/></b></div>
    <p><GameIcon name="knight" size={16}/>{strength} active strength <span>against {cityPositions.size} cities</span></p>
    {last&&<p className="ck-battle-result" role="status">{last.repelled?'Barbarians repelled':'Barbarians breached the cities'} · {last.defense} strength / {last.cities} cities{last.pillagedPlayerIds?.length?` · Pillaged: ${last.pillagedPlayerIds.map(id=>game.players.find(p=>p.id===id)?.name).join(', ')}`:''}{last.defenderIds?.length?` · Defenders: ${last.defenderIds.map(id=>game.players.find(p=>p.id===id)?.name).join(', ')}`:''}</p>}
    {!b.attacked&&<p className="ck-muted">The robber{game.seafarers?' and pirate':''} enter after the first barbarian attack.</p>}
  </section>;
}
export default function CitiesKnightsPanel({game,playerId,legalActions=[],selectedAction,setSelectedAction,knightSource,onAction,onResolve,paused,replay=false,choiceVariant,onChoiceVariant}) {const [target,setTarget]=useState(''),[resource,setResource]=useState('');const state=game.citiesKnights;if(!state)return null;
  const player=game.players.find(p=>p.id===playerId);const can=type=>!replay&&!game.pendingChoice&&legalActions.some(a=>a.type===type);const choose=type=>setSelectedAction(selectedAction===type?null:type);const offers=legalActions.filter(a=>a.type==='offerCommercialHarbor');const targets=[...new Set(offers.map(a=>a.payload.targetPlayerId))];const currentTarget=targets.includes(target)?target:targets[0];const resources=[...new Set(offers.filter(a=>a.payload.targetPlayerId===currentTarget).map(a=>a.payload.resource))];const currentResource=resources.includes(resource)?resource:resources[0];
  return <section className="ck-panel" aria-label="Cities & Knights"><h3>Cities & Knights</h3>{!game.seafarers&&<p><GameIcon name="trophy" size={16}/>13 victory points to win</p>}
    {!replay&&<CitiesKnightsChoice variant={choiceVariant} onVariantChange={onChoiceVariant} key={game.pendingChoice?.id} choice={game.pendingChoice} playerId={playerId} players={game.players} onResolve={onResolve} paused={paused}/>}
    <BarbarianVoyage game={game}/>
    {state.merchant.ownerId&&<p><GameIcon name="trade" size={17}/>{game.players.find(p=>p.id===state.merchant.ownerId)?.name} holds the Merchant · 1 VP</p>}
    {state.merchantFleet?.ownerId&&<p><GameIcon name="ship" size={17}/>{game.players.find(p=>p.id===state.merchantFleet.ownerId)?.name}: {friendly(state.merchantFleet.type)} at 2:1 this turn</p>}
    {player&&<><div className="ck-improvements">{CITY_TRACKS.map(track=>{const level=player.cityImprovements?.[track.id]||0,actions=legalActions.filter(a=>a.type==='improveCity'&&a.payload.track===track.id);return <div className={`ck-improvement track-${track.id}`} key={track.id}><div><GameIcon name={track.id} size={18}/><strong>{track.name}</strong><span>{level} / 5</span></div><div className="ck-levels" aria-label={`${track.name} level ${level} of 5`}>{[1,2,3,4,5].map(n=><i key={n} className={n<=level?'is-built':''}/>)}</div>{can('improveCity')&&actions.length>0&&<button type="button" disabled={paused} aria-pressed={selectedAction===`improveCity:${track.id}`} onClick={()=>actions.length===1?onAction(actions[0]):choose(`improveCity:${track.id}`)}>Improve <CityCost cost={{[track.commodity]:level+1}}/></button>}{level>=3&&<small>{track.ability}</small>}</div>;})}</div>
    {!replay&&<div className="ck-build-actions">{Object.entries(CK_ACTION_NAMES).filter(([type])=>type!=='improveCity'&&can(type)).map(([type,label])=><button type="button" key={type} aria-pressed={selectedAction===type} disabled={paused} onClick={()=>choose(type)}><GameIcon name={type==='buildCityWall'?'wall':'knight'} size={23}/><span>{type==='driveRobber'&&!game.seafarers?'Drive away robber':label}</span><CityCost cost={CK_ACTION_COSTS[type]}/></button>)}</div>}
    {CK_ACTION_NAMES[String(selectedAction).split(':')[0]]&&<p className="ck-instruction">{['moveKnight','driveRobber'].includes(selectedAction)?knightSource?'Choose a highlighted destination.':'Choose a highlighted active knight.':'Choose a highlighted location on the board.'}</p>}
    {!!offers.length&&<div className="ck-commercial"><h4>Commercial Harbor</h4><label>Offer to<select value={currentTarget||''} onChange={e=>setTarget(e.target.value)}>{targets.map(id=><option key={id} value={id}>{game.players.find(p=>p.id===id)?.name}</option>)}</select></label><label>Your resource<select value={currentResource||''} onChange={e=>setResource(e.target.value)}>{resources.map(r=><option key={r} value={r}>{friendly(r)}</option>)}</select></label><button type="button" className="room-primary-button" disabled={paused} onClick={()=>onAction(offers.find(a=>a.payload.targetPlayerId===currentTarget&&a.payload.resource===currentResource))}>Offer for a commodity</button></div>}
    </>}
    {player&&<div className="ck-knight-supply" aria-label="Knights remaining">{[1,2,3].map(strength=><span key={strength}><svg viewBox="-20 -22 40 42" aria-hidden="true"><KnightShape color={player.color} strength={strength}/></svg><span>{['Basic','Strong','Mighty'][strength-1]}<strong>{2-Object.values(state.knights).filter(k=>k.ownerId===playerId&&k.strength===strength).length} left</strong></span></span>)}</div>}
    <details><summary>Knights, improvements & defenses</summary><p>Recruit and promote for 1 wool + 1 ore. Activate for 1 grain. A knight activated this turn defends against barbarians but cannot act until a later turn.</p><p>City walls cost 2 brick and protect two extra cards each from a seven. A metropolis adds 2 VP and protects its city from pillaging.</p><div className="ck-table-progress">{game.players.map(p=><div key={p.id}><strong style={{color:p.color}}>{p.name}</strong><span>{CITY_TRACKS.map(t=>`${t.name} ${p.cityImprovements?.[t.id]||0}`).join(' · ')}</span><span>{p.defenderPoints||0} Defender VP · {Object.values(state.knights).filter(k=>k.ownerId===p.id&&k.active).reduce((n,k)=>n+k.strength,0)} active strength</span>{(p.progressVictoryCards||[]).map((card,i)=><span key={i}><GameIcon name="trophy" size={13}/>{friendly(card.type)} · 1 VP</span>)}</div>)}</div>{CITY_TRACKS.map(t=>{const metro=state.metropolises[t.id];return <p key={t.id}>{t.name} metropolis: {metro?.ownerId?game.players.find(p=>p.id===metro.ownerId)?.name:'Unclaimed'}{metro?.permanent?' · secured at level 5':''}</p>;})}<div className="ck-knight-key">{[1,2,3].map(s=><span key={s}><svg viewBox="-20 -22 40 42"><KnightShape strength={s} active/></svg>{['Basic','Strong','Mighty'][s-1]}</span>)}</div></details>
  </section>;
}
